[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Chris Sims <chris@jcsi.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"